name: Run CI
on: [push]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: setup
        run: bin/ci/setup.sh

      - name: test
        run: bin/ci/test.sh
